function renderLicenseBadge(license) {
  if (license != 'None') {
  return `![badge](https://img.shields.io/badge/license-${license}-brightgreen)`
  } else 
  return ``;
  }

function renderLicenseSection(license) {
  if (license != 'None') {  
  return (
    `This application is covered by the ${license} license.`
    )} else 
      return `No license has been selected.`;
      }

// TODO: Create a function to generate markdown for README
function generateMarkdown(answers) {
  return `

  <h1 align="center">${answers.title} </h1>

  ${renderLicenseBadge(answers.license)}
  
  ## Description
  
  ${answers.description}
  
  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contribution)
  - [Tests](#testing)
  - [Questions](#questions)
  
  ## Installation
  ${answers.installation}
  
  ## Usage
  ${answers.usage}
  
  ## License
  ${renderLicenseBadge(answers.license)}
  ${renderLicenseSection(answers.license)}
  
  ## Contributing
  ${answers.contribution}
  
  ## Tests
  ${answers.testing}
 
  ## Questions
  <br />
  If you have any questions, comments, or concerns: <br />
  <br />
  Find me on GitHub: [${answers.github}](https://github.com/${answers.github})<br />
  <br />
  Email me with any questions: ${answers.email}<br /><br />
  This README was generated by [README-Generator](https://github.com/lkalicki/readme-generator)
      `;
    }

module.exports = generateMarkdown;
